
--B
CREATE DATABASE BlueJacket
GO
USE BlueJacket
GO
--create table
CREATE TABLE MsStaff(
	StaffID CHAR(5) PRIMARY KEY NOT NULL CHECK (StaffID LIKE 'MS[0-9][0-9][0-9]'),
	StaffName VARCHAR(100) NOT NULL,
	StaffEmail VARCHAR(50)NOT NULL ,
	StaffGender VARCHAR(10) NOT NULL CHECK (StaffGender LIKE 'Male' OR StaffGender LIKE 'Female'),
	StaffPhone VARCHAR(20)NOT NULL CHECK (ISNUMERIC(StaffPhone)=1 ),
	StaffSalary INT NOT NULL CHECK (StaffSalary BETWEEN 4000000 AND 100000000)
)
CREATE TABLE MsCustomer(
	CustomerID CHAR(5) PRIMARY KEY NOT NULL CHECK (CustomerID LIKE 'MC[0-9][0-9][0-9]'),
	CustomerName VARCHAR(30) NOT NULL,
	CustomerGender VARCHAR(10) NOT NULL CHECK (CustomerGender LIKE 'Male' OR CustomerGender LIKE 'Female'),
	CustomerPhone VARCHAR(20) NOT NULL CHECK (ISNUMERIC(CustomerPhone)=1),
	CustomerAddress VARCHAR(50) NOT NULL CHECK (CustomerAddress LIKE '% Street %')
	)
CREATE TABLE MsVendor (
	VendorID CHAR(5) PRIMARY KEY NOT NULL CHECK (VendorID LIKE 'MV[0-9][0-9][0-9]'),
	VendorName VARCHAR(20) NOT NULL,
	VendorEmail VARCHAR(50) NOT NULL,
	VendorPhone VARCHAR(20) NOT NULL CHECK (ISNUMERIC(VendorPhone)=1),
	VendorAddress VARCHAR(50) NOT NULL
	)
CREATE TABLE MsJacketBrand(
	JacketBrandID CHAR(5) PRIMARY KEY NOT NULL CHECK (JacketBrandID LIKE 'JB[0-9][0-9][0-9]'),
	JacketBrandName VARCHAR(20) NOT NULL
)
CREATE TABLE MsJacketType(
	JacketTypeID CHAR(5) PRIMARY KEY NOT NULL CHECK (JacketTypeID LIKE 'JT[0-9][0-9][0-9]'),
	JacketTypeName VARCHAR(20) NOT NULL
	)
CREATE TABLE MsJacket(
	JacketID CHAR(5) PRIMARY KEY NOT NULL CHECK(JacketID LIKE 'MJ[0-9][0-9][0-9]'),
	PurchasePrice INT NOT NULL CHECK  (PurchasePrice BETWEEN 0 and 500000000),
	SalesPrice INT NOT NULL CHECK (SalesPrice BETWEEN 0 and 500000000),
	JacketStock INT NOT NULL CHECK (JacketStock BETWEEN 0 and 1000),
	JacketBrandID CHAR(5) NOT NULL FOREIGN KEY REFERENCES MsJacketBrand(JacketBrandID) ON UPDATE CASCADE ON DELETE CASCADE,
	JacketTypeID CHAR(5)  NOT NULL FOREIGN KEY REFERENCES MsJacketType(JacketTypeID) ON UPDATE CASCADE ON DELETE CASCADE
)
CREATE TABLE PurchaseHeader(
	PurchaseID CHAR(5) PRIMARY KEY NOT NULL CHECK (PurchaseID LIKE 'PH[0-9][0-9][0-9]'),
	StaffID CHAR(5) NOT NULL FOREIGN KEY REFERENCES MsStaff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE,
	VendorID CHAR(5) NOT NULL FOREIGN KEY REFERENCES MsVendor(VendorID) ON UPDATE CASCADE ON DELETE CASCADE,
	PurchaseDate DATE NOT NULL CHECK (DATENAME(WEEKDAY, PurchaseDate) NOT LIKE 'Sunday')
)
CREATE TABLE SalesHeader (
	SalesID CHAR(5) PRIMARY KEY NOT NULL CHECK (SalesID LIKE 'SH[0-9][0-9][0-9]'),
	StaffID CHAR(5) NOT NULL FOREIGN KEY REFERENCES MsStaff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE,
	CustomerID CHAR(5) NOT NULL FOREIGN KEY REFERENCES MsCustomer(CustomerID) ON UPDATE CASCADE ON DELETE CASCADE,
	SalesDate DATE NOT NULL CHECK (DATENAME(WEEKDAY, SalesDate) NOT LIKE 'Sunday')
	)
CREATE TABLE SalesDetail (
	SalesID CHAR(5) FOREIGN KEY REFERENCES SalesHeader(SalesID) ON UPDATE CASCADE ON DELETE CASCADE,
	JacketID CHAR(5) FOREIGN KEY REFERENCES MsJacket(JacketID) ON UPDATE CASCADE ON DELETE CASCADE,
	SalesQuantity INT NOT NULL CHECK (SalesQuantity BETWEEN 0 AND 100),
	PRIMARY KEY(SalesID,JacketID)
	)
CREATE TABLE PurchaseDetail (
	PurchaseID CHAR(5) FOREIGN KEY REFERENCES PurchaseHeader(PurchaseID) ON UPDATE CASCADE ON DELETE CASCADE,
	JacketID CHAR(5) FOREIGN KEY REFERENCES MsJacket(JacketID) ON UPDATE CASCADE ON DELETE CASCADE,
	PurchaseQuantity INT NOT NULL CHECK (PurchaseQuantity BETWEEN 0 AND 100),
	PRIMARY KEY(PurchaseID,JacketID)
	)